### Style
#
# Nordic colors
#
set $bg         #2E3440
set $fg         #D8DEE9
set $border     #88C0D0
set $inactive   #4C566A
set $urgent     #BF616A

client.focused          $border $border $fg $border $border
client.focused_inactive $inactive $inactive $fg $inactive $inactive
client.unfocused        $inactive $inactive $fg $inactive $inactive
client.urgent           $urgent $urgent $fg $urgent $urgent

#
# Borders
#
default_border pixel 2
default_floating_border pixel 2

#
# Gaps
#
gaps inner 4
gaps outer 4
